### ISSUE TITLE
Question. Is there a way to port this theme to VSCode ?

### ISSUE THREAD

**Issue by dziku86** [trvswgnr/codepen-brackets-theme#2]
Is there a painless way to port this theme to VSCode ?
I looked everywhere for a VSCode theme based on Codepen Twilight and there is none.

**Comment by Wujek280** [comment]
I did it hard way when i switched from brackets to VSC

Basically downloaded another theme and chage it's variables to matching, took while but was worth it back then.

Maybe someone has done it arleady, i did it +1yr ago.

**Comment by Wujek280** [comment]
I have found it
https://gist.github.com/Wujek280/544d79511a117d7d6cca3cbe53da46c8
if its still relevant and there is no existing theme like this I could make fully fledged theme out of it in spare time.
I think you need to tweak some colors in settings.json as well

**Comment by dziku86** [comment]
That's awesome, thank you!  I'll try to make it tonight.

**Comment by Wujek280** [comment]
Basically in CP terms of service there is note, that you cannot make derivative works based on their service so maybe that explains why there is no such theme available on marketplace.

**Comment by dziku86** [comment]
Didn't even crossed my mind... I'll ask them first if I can put it on github.

**Comment by trvswgnr** [comment]
i ported this to vscode last year since i switched. it doesn’t use CodeMirror so it’s not perfect but definitely usable.

**Comment by dziku86** [comment]
> i ported this to vscode last year since i switched. it doesn’t use CodeMirror so it’s not perfect but definitely usable.

@trvswgnr Could you share it?
I didn't had time to make it so I've switched to Gruvbox Dark Hard and it looks kinda cool:

![image](https://user-images.githubusercontent.com/56586404/106287543-3406e800-6247-11eb-95e6-f46375ecce5f.png)
